name: Build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'src/**/*'
      - 'public/**/*'
      - 'package.json'
      - 'package-lock.json'
      - 'rollup.config.js'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'src/**/*'
      - 'public/**/*'
      - 'package.json'
      - 'package-lock.json'
      - 'rollup.config.js'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
